export const FILTER_CARDS_BY_CATEGORIES = "FILTER_CARDS_BY_CATEGORIES";

export const GET_CARDS_SUCCESS = "GET_CARDS_SUCCESS";
export const GET_CARDS_START = "GET_CARDS_START";
export const GET_CARDS_FAILURE = "GET_CARDS_FAILURE";

export const POST_CARD_TO_BASKET_FAILURE = "POST_CARD_TO_BASKET_FAILURE";
export const POST_CARD_TO_BASKET_START = "POST_CARD_TO_BASKET_START";
export const POST_CARD_TO_BASKET_SUCCESS = "POST_CARD_TO_BASKET_SUCCESS";

export const GET_CARDS_FROM_BASKET_SUCCESS = "GET_CARDS_FROM_BASKET_SUCCESS";

export const DELETE_CARD_FROM_CART = "DELETE_CARD_FROM_CART";

export const COUNT_TOTAL_PRICE = "COUNT_TOTAL_PRICE";

export const FILTERED_CARDS = "FILTERED_CARDS";

export const TRENDING_CARD = "TRENDING_CARD";
